CREATE DATABASE IF NOT EXISTS tvms;
USE tvms;

CREATE TABLE IF NOT EXISTS users (
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('admin', 'officer', 'violator') NOT NULL DEFAULT 'officer',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
